version: '1.0.{build}'

image: Visual Studio 2015

platform:
    - x64
    
configuration:
    - Debug
    - Release

environment:
    matrix:
        # на 2015 VS
        - TOOLCHAIN: msvc14

install:
    # скрипт настройки среды и установки зависимостей:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%
    - call ci\appveyor\install.bat

build_script:
    # скрипт сборки проекта:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%     # содержит нужный CMake-генератор
    - cmake --build . %CMAKE_BUILD_FLAGS%  # задаёт конфигурацию Debug/Release
